{"name": "test_fail7", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail7():\n>       assert False\nE       assert False\n\ntest_fail.py:20: AssertionError"}, "start": 1747922923533, "stop": 1747922923533, "uuid": "77673e64-ff05-4293-bdbd-867942bd79f3", "historyId": "e5476871c2923afbd50a8191a77cef77", "testCaseId": "e5476871c2923afbd50a8191a77cef77", "fullName": "tests.simple.test_fail#test_fail7", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Pro-Nikita.local"}, {"name": "thread", "value": "18636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}